# Use the official Go image as the base image
FROM golang:1.20

# Copy all files from the main project into the container
COPY . /app

# Set the working directory
WORKDIR /app

# Download the dependencies for the project
RUN go mod download

# Build project
RUN go build -o main .

# Expose port 8080 for incoming connections
EXPOSE 8080

# Start the project
CMD ["./main"]
